/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculadora_Calculadora */

#ifndef _Included_calculadora_Calculadora
#define _Included_calculadora_Calculadora
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class calculadora_Operaciones */

#ifndef _Included_calculadora_Operaciones
#define _Included_calculadora_Operaciones
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculadora_Operaciones
 * Method:    getSuma
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadora_Operaciones_getSuma
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadora_Operaciones
 * Method:    getResta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadora_Operaciones_getResta
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadora_Operaciones
 * Method:    getMulplicacion
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadora_Operaciones_getMulplicacion
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadora_Operaciones
 * Method:    getDivision
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadora_Operaciones_getDivision
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
